export const education = [
  {
    id: 1,
    school: "Arizona State University",
    degree: "Master of Science",
    field: "Computer Science",
    location: "Tempe, Arizona",
    startDate: "Aug 2024",
    endDate: "May 2026",
    gpa: "4.00/4.00",
    current: true,
    logo: "/images/asu-logo.png",
    description: "Perfect GPA with focus on cloud computing and AI/ML",
    coursework: [
      "Cloud Computing",
      "Distributed Systems",
      "Machine Learning",
      "Software Engineering",
      "Data Structures & Algorithms",
    ],
  },
  {
    id: 2,
    school: "Visvesvaraya Technological University",
    degree: "Bachelor of Engineering",
    field: "Information Science Engineering",
    location: "India",
    startDate: "Aug 2017",
    endDate: "May 2021",
    gpa: "9.07/10.0",
    current: false,
    logo: "/images/vtu-logo.png",
    description: "Strong foundation in computer science and software engineering",
    coursework: [
      "Data Structures",
      "Database Management",
      "Operating Systems",
      "Computer Networks",
      "Web Technologies",
    ],
  },
];

export const certifications = [
  {
    id: 1,
    name: "AWS Solutions Architect",
    issuer: "Amazon Web Services",
    year: 2025,
    credentialUrl: "#",
    logo: "/images/aws-saa.png",
    description: "Expertise in designing distributed systems on AWS",
  },
  {
    id: 2,
    name: "AWS Cloud Practitioner",
    issuer: "Amazon Web Services",
    year: 2025,
    credentialUrl: "#",
    logo: "/images/aws-cp.png",
    description: "Foundational understanding of AWS Cloud",
  },
  {
    id: 3,
    name: "Data Analytics Consulting Virtual Internship",
    issuer: "KPMG",
    year: 2024,
    credentialUrl: "#",
    logo: "/images/kpmg.png",
    description: "Data analysis and business consulting skills",
  },
];
