export const experience = [
  {
    id: 1,
    company: "ASU Cloud Innovation Center",
    position: "AWS Cloud Developer",
    location: "Scottsdale, Arizona",
    startDate: "Apr 2025",
    endDate: "Present",
    current: true,
    description: "Leading cloud architecture and AI/ML solution development",
    highlights: [
      "Led end-to-end delivery of AI/ML and cloud projects, researching and selecting optimal AWS services (Bedrock, SageMaker, Lambda, DynamoDB) tailored to diverse enterprise client needs",
      "Built full-stack cloud solutions using Infrastructure as Code (CloudFormation/Terraform), API-driven backends, and responsive frontends with React and Streamlit",
      "Designed and deployed scalable, cost-effective AWS architectures, ensuring fast integration into client environments and earning direct client commendations",
      "Reduced release cycles from 7 days to 24 hours by automating CI/CD pipelines with CodeCommit, CodeBuild, and CodeDeploy, increasing deployment velocity 6×",
    ],
    techStack: [
      "AWS",
      "React",
      "Python",
      "Terraform",
      "CloudFormation",
      "CI/CD",
      "Lambda",
      "DynamoDB",
      "Bedrock",
      "SageMaker",
    ],
    type: "Full-time",
  },
  {
    id: 2,
    company: "Oracle Cerner",
    position: "Software Engineer",
    location: "Bangalore, India",
    startDate: "May 2021",
    endDate: "Jul 2024",
    current: false,
    description: "Developed enterprise healthcare applications with 100% compliance",
    highlights: [
      "Delivered code for healthcare applications, maintaining a 100% compliance rate with safety and regulatory standards",
      "Developed and maintained Java-based microservices using Spring Boot, powering backend systems for critical radiology workflows in enterprise healthcare applications",
      "Collaborated with cross-functional teams of engineers, clinicians, and product managers to support operations logistics and deliver project updates",
      "Streamlined reporting processes by generating automated status reports using Python, Java, and Excel, improving stakeholder communication efficiency by 25%",
      "Played a key role in backend modernization efforts, contributing to a faster, more reliable radiology system used by thousands of practitioners daily",
    ],
    techStack: [
      "Java",
      "Spring Boot",
      "Python",
      "Microservices",
      "Healthcare",
      "SQL",
      "REST APIs",
    ],
    type: "Full-time",
  },
];
