export const featuredProjects = [
  {
    id: 1,
    name: "Bilingual AI Chatbot: Crohn's & Colitis Foundation",
    slug: "crohns-colitis-chatbot",
    description:
      "Bilingual conversational AI chatbot enabling patients, caregivers, and healthcare providers to access trusted information about inflammatory bowel disease (IBD). Reduces navigation complexity with instant responses and human follow-up for out-of-scope questions.",
    longDescription:
      "Collaborated with the Crohn's & Colitis Foundation to design a bilingual conversational AI chatbot powered by AWS. The solution provides instant access to trusted information about Crohn's disease and ulcerative colitis, significantly reducing website navigation complexity and improving patient support.",
    techStack: [
      "AWS",
      "CloudFormation",
      "AWS Databases",
      "AI/ML",
      "NLP",
      "Lambda",
      "API Gateway",
      "Bilingual NLP",
    ],
    features: [
      "Bilingual support (English & Spanish)",
      "Trusted IBD information access",
      "Reduced navigation complexity",
      "Instant response system",
      "Human follow-up for complex queries",
      "Healthcare provider support",
      "Patient and caregiver assistance",
      "AWS-powered infrastructure",
    ],
    githubUrl: "https://github.com/ASUCICREPO/Crohns-Colitis-Project",
    demoUrl: null,
    imageUrl: "/images/projects/crohns-colitis.png",
    featured: true,
    year: 2025,
    category: "AI/ML",
  },
  {
    id: 2,
    name: "Knowledge Bot - Disability Rights Texas",
    slug: "disability-rights-texas-knowledge-bot",
    description:
      "AI chatbot with Amazon Q Business reducing legal inquiry load by 40%+. Enables 24/7 access to legal rights info for 10K+ users in English and Spanish with improved clarity through citations and simplification.",
    longDescription:
      "Built an intelligent AI chatbot using Amazon Q Business to provide accessible legal information for Disability Rights Texas. The solution significantly reduced the legal inquiry workload while making critical information available 24/7 to thousands of users in multiple languages.",
    techStack: [
      "AWS Q Business",
      "S3",
      "Lambda",
      "API Gateway",
      "AI/ML",
      "NLP",
      "Python",
    ],
    features: [
      "40%+ reduction in legal inquiry load",
      "24/7 access to critical legal resources",
      "10K+ users served",
      "Bilingual support (English & Spanish)",
      "60% boost in engagement",
      "Citation support for accuracy",
    ],
    githubUrl: "https://github.com/ASUCICREPO/Disability-Rights-Texas",
    demoUrl: null,
    imageUrl: "/images/projects/knowledge-bot.png",
    featured: true,
    year: 2025,
    category: "AI/ML",
  },
  {
    id: 3,
    name: "Credit Card Reader Using Facial Recognition",
    slug: "credit-card-facial-recognition",
    description:
      "Face recognition service with 99.8% LFW accuracy using DeepFace library. Deployed on EC2 with auto-scaling and reduced spoofing attacks by 70% through liveness detection with temporal CNN.",
    longDescription:
      "Developed a secure facial authentication system for credit card verification using advanced computer vision techniques. The system achieves exceptional accuracy while preventing fraud through sophisticated liveness detection.",
    techStack: [
      "Python",
      "DeepFace",
      "AWS EC2",
      "Computer Vision",
      "CNN",
      "TensorFlow",
      "OpenCV",
    ],
    features: [
      "99.8% accuracy on LFW dataset",
      "70% reduction in spoofing attacks",
      "Liveness detection with temporal CNN",
      "Auto-scaling deployment on AWS EC2",
      "Real-time face verification",
      "High security authentication",
    ],
    githubUrl: "https://github.com/KHemanthRaju/Credit-Card-Reader-Using-Facial-Recognition",
    demoUrl: null,
    imageUrl: "/images/projects/facial-recognition.png",
    featured: true,
    stars: 18,
    year: 2021,
    category: "AI/ML",
  },
  {
    id: 4,
    name: "AI-PPT-Generator",
    slug: "ai-ppt-generator",
    description:
      "AI-powered PowerPoint generator using Amazon Bedrock (Claude & Nova Canvas). Automatically creates professional presentations with AI-generated content and images using AWS Lambda and S3.",
    longDescription:
      "Created an automated presentation generation system leveraging Amazon Bedrock's generative AI capabilities. The system generates both compelling content and relevant images to create complete professional presentations.",
    techStack: [
      "Python",
      "AWS Bedrock",
      "Lambda",
      "S3",
      "Claude AI",
      "Nova Canvas",
      "Generative AI",
    ],
    features: [
      "Automated content generation",
      "AI-generated images with Nova Canvas",
      "Professional template design",
      "Serverless architecture",
      "Fast generation times",
      "Cost-effective solution",
    ],
    githubUrl: "https://github.com/KHemanthRaju/AI-PPT-Generator",
    demoUrl: null,
    imageUrl: "/images/projects/ai-ppt-generator.png",
    featured: true,
    year: 2025,
    category: "AI/ML",
  },
  {
    id: 5,
    name: "RAG Visualizer",
    slug: "rag-visualizer",
    description:
      "Interactive demonstration of Retrieval-Augmented Generation (RAG) pipeline. Visualizes document processing through chunking, embedding, vector DB storage, and intelligent querying with real-time pipeline tracking.",
    longDescription:
      "Built an educational tool to help developers understand RAG systems by providing real-time visualization of the entire pipeline from document ingestion to query response. Features interactive components for each stage of the process.",
    techStack: [
      "TypeScript",
      "React",
      "Vector DB",
      "Embeddings",
      "RAG",
      "Next.js",
      "Tailwind CSS",
    ],
    features: [
      "Real-time pipeline visualization",
      "Document chunking demonstration",
      "Embedding generation display",
      "Vector database operations",
      "Query processing walkthrough",
      "Educational resource",
    ],
    githubUrl: "https://github.com/KHemanthRaju/RAG_Visualizer",
    demoUrl: null,
    imageUrl: "/images/projects/rag-visualizer.png",
    featured: true,
    year: 2025,
    category: "AI/ML",
  },
];
